#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopitalGestionLinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class HopitalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertChambre(Chambre instance);
    partial void UpdateChambre(Chambre instance);
    partial void DeleteChambre(Chambre instance);
    partial void InsertTraitement(Traitement instance);
    partial void UpdateTraitement(Traitement instance);
    partial void DeleteTraitement(Traitement instance);
    partial void InsertChirurgie(Chirurgie instance);
    partial void UpdateChirurgie(Chirurgie instance);
    partial void DeleteChirurgie(Chirurgie instance);
    partial void InsertConsultation(Consultation instance);
    partial void UpdateConsultation(Consultation instance);
    partial void DeleteConsultation(Consultation instance);
    partial void InsertExamenBiologique(ExamenBiologique instance);
    partial void UpdateExamenBiologique(ExamenBiologique instance);
    partial void DeleteExamenBiologique(ExamenBiologique instance);
    partial void InsertExamenRadiologique(ExamenRadiologique instance);
    partial void UpdateExamenRadiologique(ExamenRadiologique instance);
    partial void DeleteExamenRadiologique(ExamenRadiologique instance);
    partial void InsertFacture(Facture instance);
    partial void UpdateFacture(Facture instance);
    partial void DeleteFacture(Facture instance);
    partial void InsertHopital(Hopital instance);
    partial void UpdateHopital(Hopital instance);
    partial void DeleteHopital(Hopital instance);
    partial void InsertHospitalisation(Hospitalisation instance);
    partial void UpdateHospitalisation(Hospitalisation instance);
    partial void DeleteHospitalisation(Hospitalisation instance);
    partial void InsertMedecin(Medecin instance);
    partial void UpdateMedecin(Medecin instance);
    partial void DeleteMedecin(Medecin instance);
    partial void InsertMedecin1(Medecin1 instance);
    partial void UpdateMedecin1(Medecin1 instance);
    partial void DeleteMedecin1(Medecin1 instance);
    partial void InsertPatient(Patient instance);
    partial void UpdatePatient(Patient instance);
    partial void DeletePatient(Patient instance);
    partial void InsertPrescription(Prescription instance);
    partial void UpdatePrescription(Prescription instance);
    partial void DeletePrescription(Prescription instance);
    partial void InsertRdv(Rdv instance);
    partial void UpdateRdv(Rdv instance);
    partial void DeleteRdv(Rdv instance);
    #endregion
		
		public HopitalDataContext() : 
				base(global::HopitalGestionLinqToSql.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HopitalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HopitalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HopitalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HopitalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Chambre> Chambre
		{
			get
			{
				return this.GetTable<Chambre>();
			}
		}
		
		public System.Data.Linq.Table<Traitement> Traitement
		{
			get
			{
				return this.GetTable<Traitement>();
			}
		}
		
		public System.Data.Linq.Table<Chirurgie> Chirurgie
		{
			get
			{
				return this.GetTable<Chirurgie>();
			}
		}
		
		public System.Data.Linq.Table<Consultation> Consultation
		{
			get
			{
				return this.GetTable<Consultation>();
			}
		}
		
		public System.Data.Linq.Table<ExamenBiologique> ExamenBiologique
		{
			get
			{
				return this.GetTable<ExamenBiologique>();
			}
		}
		
		public System.Data.Linq.Table<ExamenRadiologique> ExamenRadiologique
		{
			get
			{
				return this.GetTable<ExamenRadiologique>();
			}
		}
		
		public System.Data.Linq.Table<Facture> Facture
		{
			get
			{
				return this.GetTable<Facture>();
			}
		}
		
		public System.Data.Linq.Table<Hopital> Hopital
		{
			get
			{
				return this.GetTable<Hopital>();
			}
		}
		
		public System.Data.Linq.Table<Hospitalisation> Hospitalisation
		{
			get
			{
				return this.GetTable<Hospitalisation>();
			}
		}
		
		public System.Data.Linq.Table<Medecin> Medecin
		{
			get
			{
				return this.GetTable<Medecin>();
			}
		}
		
		public System.Data.Linq.Table<Medecin1> Medecin1
		{
			get
			{
				return this.GetTable<Medecin1>();
			}
		}
		
		public System.Data.Linq.Table<Patient> Patient
		{
			get
			{
				return this.GetTable<Patient>();
			}
		}
		
		public System.Data.Linq.Table<Prescription> Prescription
		{
			get
			{
				return this.GetTable<Prescription>();
			}
		}
		
		public System.Data.Linq.Table<Rdv> Rdv
		{
			get
			{
				return this.GetTable<Rdv>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chambre")]
	public partial class Chambre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _etage;
		
		private System.Nullable<int> _capacite;
		
		private System.Nullable<decimal> _prix;
		
		private System.Nullable<int> _occupe;
		
		private System.Nullable<int> _idHopital;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnetageChanging(System.Nullable<int> value);
    partial void OnetageChanged();
    partial void OncapaciteChanging(System.Nullable<int> value);
    partial void OncapaciteChanged();
    partial void OnprixChanging(System.Nullable<decimal> value);
    partial void OnprixChanged();
    partial void OnoccupeChanging(System.Nullable<int> value);
    partial void OnoccupeChanged();
    partial void OnidHopitalChanging(System.Nullable<int> value);
    partial void OnidHopitalChanged();
    #endregion
		
		public Chambre()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etage", DbType="Int")]
		public System.Nullable<int> etage
		{
			get
			{
				return this._etage;
			}
			set
			{
				if ((this._etage != value))
				{
					this.OnetageChanging(value);
					this.SendPropertyChanging();
					this._etage = value;
					this.SendPropertyChanged("etage");
					this.OnetageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacite", DbType="Int")]
		public System.Nullable<int> capacite
		{
			get
			{
				return this._capacite;
			}
			set
			{
				if ((this._capacite != value))
				{
					this.OncapaciteChanging(value);
					this.SendPropertyChanging();
					this._capacite = value;
					this.SendPropertyChanged("capacite");
					this.OncapaciteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this.OnprixChanging(value);
					this.SendPropertyChanging();
					this._prix = value;
					this.SendPropertyChanged("prix");
					this.OnprixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_occupe", DbType="Int")]
		public System.Nullable<int> occupe
		{
			get
			{
				return this._occupe;
			}
			set
			{
				if ((this._occupe != value))
				{
					this.OnoccupeChanging(value);
					this.SendPropertyChanging();
					this._occupe = value;
					this.SendPropertyChanged("occupe");
					this.OnoccupeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHopital", DbType="Int")]
		public System.Nullable<int> idHopital
		{
			get
			{
				return this._idHopital;
			}
			set
			{
				if ((this._idHopital != value))
				{
					this.OnidHopitalChanging(value);
					this.SendPropertyChanging();
					this._idHopital = value;
					this.SendPropertyChanged("idHopital");
					this.OnidHopitalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Traitement")]
	public partial class Traitement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<decimal> _prix;
		
		private System.Nullable<int> _idPatient;
		
		private System.Nullable<int> _idMedecin;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnprixChanging(System.Nullable<decimal> value);
    partial void OnprixChanged();
    partial void OnidPatientChanging(System.Nullable<int> value);
    partial void OnidPatientChanged();
    partial void OnidMedecinChanging(System.Nullable<int> value);
    partial void OnidMedecinChanged();
    #endregion
		
		public Traitement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this.OnprixChanging(value);
					this.SendPropertyChanging();
					this._prix = value;
					this.SendPropertyChanged("prix");
					this.OnprixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPatient", DbType="Int")]
		public System.Nullable<int> idPatient
		{
			get
			{
				return this._idPatient;
			}
			set
			{
				if ((this._idPatient != value))
				{
					this.OnidPatientChanging(value);
					this.SendPropertyChanging();
					this._idPatient = value;
					this.SendPropertyChanged("idPatient");
					this.OnidPatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedecin", DbType="Int")]
		public System.Nullable<int> idMedecin
		{
			get
			{
				return this._idMedecin;
			}
			set
			{
				if ((this._idMedecin != value))
				{
					this.OnidMedecinChanging(value);
					this.SendPropertyChanging();
					this._idMedecin = value;
					this.SendPropertyChanged("idMedecin");
					this.OnidMedecinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chirurgie")]
	public partial class Chirurgie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idChirurgien;
		
		private System.Nullable<int> _idAnesthesiste;
		
		private System.Nullable<int> _idTraitement;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidChirurgienChanging(System.Nullable<int> value);
    partial void OnidChirurgienChanged();
    partial void OnidAnesthesisteChanging(System.Nullable<int> value);
    partial void OnidAnesthesisteChanged();
    partial void OnidTraitementChanging(System.Nullable<int> value);
    partial void OnidTraitementChanged();
    #endregion
		
		public Chirurgie()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idChirurgien", DbType="Int")]
		public System.Nullable<int> idChirurgien
		{
			get
			{
				return this._idChirurgien;
			}
			set
			{
				if ((this._idChirurgien != value))
				{
					this.OnidChirurgienChanging(value);
					this.SendPropertyChanging();
					this._idChirurgien = value;
					this.SendPropertyChanged("idChirurgien");
					this.OnidChirurgienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAnesthesiste", DbType="Int")]
		public System.Nullable<int> idAnesthesiste
		{
			get
			{
				return this._idAnesthesiste;
			}
			set
			{
				if ((this._idAnesthesiste != value))
				{
					this.OnidAnesthesisteChanging(value);
					this.SendPropertyChanging();
					this._idAnesthesiste = value;
					this.SendPropertyChanged("idAnesthesiste");
					this.OnidAnesthesisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTraitement", DbType="Int")]
		public System.Nullable<int> idTraitement
		{
			get
			{
				return this._idTraitement;
			}
			set
			{
				if ((this._idTraitement != value))
				{
					this.OnidTraitementChanging(value);
					this.SendPropertyChanging();
					this._idTraitement = value;
					this.SendPropertyChanged("idTraitement");
					this.OnidTraitementChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Consultation")]
	public partial class Consultation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _synthese;
		
		private string _typeConsultation;
		
		private System.Nullable<decimal> _prix;
		
		private int _idPatient;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnsyntheseChanging(string value);
    partial void OnsyntheseChanged();
    partial void OntypeConsultationChanging(string value);
    partial void OntypeConsultationChanged();
    partial void OnprixChanging(System.Nullable<decimal> value);
    partial void OnprixChanged();
    partial void OnidPatientChanging(int value);
    partial void OnidPatientChanged();
    #endregion
		
		public Consultation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_synthese", DbType="VarChar(MAX)")]
		public string synthese
		{
			get
			{
				return this._synthese;
			}
			set
			{
				if ((this._synthese != value))
				{
					this.OnsyntheseChanging(value);
					this.SendPropertyChanging();
					this._synthese = value;
					this.SendPropertyChanged("synthese");
					this.OnsyntheseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeConsultation", DbType="VarChar(MAX)")]
		public string typeConsultation
		{
			get
			{
				return this._typeConsultation;
			}
			set
			{
				if ((this._typeConsultation != value))
				{
					this.OntypeConsultationChanging(value);
					this.SendPropertyChanging();
					this._typeConsultation = value;
					this.SendPropertyChanged("typeConsultation");
					this.OntypeConsultationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this.OnprixChanging(value);
					this.SendPropertyChanging();
					this._prix = value;
					this.SendPropertyChanged("prix");
					this.OnprixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPatient", DbType="Int NOT NULL")]
		public int idPatient
		{
			get
			{
				return this._idPatient;
			}
			set
			{
				if ((this._idPatient != value))
				{
					this.OnidPatientChanging(value);
					this.SendPropertyChanging();
					this._idPatient = value;
					this.SendPropertyChanged("idPatient");
					this.OnidPatientChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamenBiologique")]
	public partial class ExamenBiologique : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _designation;
		
		private string _resultat;
		
		private System.Nullable<int> _idTraitement;
		
		private System.Nullable<int> _idMedecin;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void OnresultatChanging(string value);
    partial void OnresultatChanged();
    partial void OnidTraitementChanging(System.Nullable<int> value);
    partial void OnidTraitementChanged();
    partial void OnidMedecinChanging(System.Nullable<int> value);
    partial void OnidMedecinChanged();
    #endregion
		
		public ExamenBiologique()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(100)")]
		public string designation
		{
			get
			{
				return this._designation;
			}
			set
			{
				if ((this._designation != value))
				{
					this.OndesignationChanging(value);
					this.SendPropertyChanging();
					this._designation = value;
					this.SendPropertyChanged("designation");
					this.OndesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultat", DbType="VarChar(MAX)")]
		public string resultat
		{
			get
			{
				return this._resultat;
			}
			set
			{
				if ((this._resultat != value))
				{
					this.OnresultatChanging(value);
					this.SendPropertyChanging();
					this._resultat = value;
					this.SendPropertyChanged("resultat");
					this.OnresultatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTraitement", DbType="Int")]
		public System.Nullable<int> idTraitement
		{
			get
			{
				return this._idTraitement;
			}
			set
			{
				if ((this._idTraitement != value))
				{
					this.OnidTraitementChanging(value);
					this.SendPropertyChanging();
					this._idTraitement = value;
					this.SendPropertyChanged("idTraitement");
					this.OnidTraitementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedecin", DbType="Int")]
		public System.Nullable<int> idMedecin
		{
			get
			{
				return this._idMedecin;
			}
			set
			{
				if ((this._idMedecin != value))
				{
					this.OnidMedecinChanging(value);
					this.SendPropertyChanging();
					this._idMedecin = value;
					this.SendPropertyChanged("idMedecin");
					this.OnidMedecinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamenRadiologique")]
	public partial class ExamenRadiologique : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _designation;
		
		private string _resultat;
		
		private System.Nullable<int> _idTraitement;
		
		private System.Nullable<int> _idMedecin;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void OnresultatChanging(string value);
    partial void OnresultatChanged();
    partial void OnidTraitementChanging(System.Nullable<int> value);
    partial void OnidTraitementChanged();
    partial void OnidMedecinChanging(System.Nullable<int> value);
    partial void OnidMedecinChanged();
    #endregion
		
		public ExamenRadiologique()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(100)")]
		public string designation
		{
			get
			{
				return this._designation;
			}
			set
			{
				if ((this._designation != value))
				{
					this.OndesignationChanging(value);
					this.SendPropertyChanging();
					this._designation = value;
					this.SendPropertyChanged("designation");
					this.OndesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultat", DbType="VarChar(MAX)")]
		public string resultat
		{
			get
			{
				return this._resultat;
			}
			set
			{
				if ((this._resultat != value))
				{
					this.OnresultatChanging(value);
					this.SendPropertyChanging();
					this._resultat = value;
					this.SendPropertyChanged("resultat");
					this.OnresultatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTraitement", DbType="Int")]
		public System.Nullable<int> idTraitement
		{
			get
			{
				return this._idTraitement;
			}
			set
			{
				if ((this._idTraitement != value))
				{
					this.OnidTraitementChanging(value);
					this.SendPropertyChanging();
					this._idTraitement = value;
					this.SendPropertyChanged("idTraitement");
					this.OnidTraitementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedecin", DbType="Int")]
		public System.Nullable<int> idMedecin
		{
			get
			{
				return this._idMedecin;
			}
			set
			{
				if ((this._idMedecin != value))
				{
					this.OnidMedecinChanging(value);
					this.SendPropertyChanging();
					this._idMedecin = value;
					this.SendPropertyChanged("idMedecin");
					this.OnidMedecinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Facture")]
	public partial class Facture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<decimal> _prix;
		
		private System.Nullable<int> _idPatient;
		
		private System.Nullable<int> _payee;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnprixChanging(System.Nullable<decimal> value);
    partial void OnprixChanged();
    partial void OnidPatientChanging(System.Nullable<int> value);
    partial void OnidPatientChanged();
    partial void OnpayeeChanging(System.Nullable<int> value);
    partial void OnpayeeChanged();
    #endregion
		
		public Facture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this.OnprixChanging(value);
					this.SendPropertyChanging();
					this._prix = value;
					this.SendPropertyChanged("prix");
					this.OnprixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPatient", DbType="Int")]
		public System.Nullable<int> idPatient
		{
			get
			{
				return this._idPatient;
			}
			set
			{
				if ((this._idPatient != value))
				{
					this.OnidPatientChanging(value);
					this.SendPropertyChanging();
					this._idPatient = value;
					this.SendPropertyChanged("idPatient");
					this.OnidPatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payee", DbType="Int")]
		public System.Nullable<int> payee
		{
			get
			{
				return this._payee;
			}
			set
			{
				if ((this._payee != value))
				{
					this.OnpayeeChanging(value);
					this.SendPropertyChanging();
					this._payee = value;
					this.SendPropertyChanged("payee");
					this.OnpayeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hopital")]
	public partial class Hopital : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    #endregion
		
		public Hopital()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(100)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hospitalisation")]
	public partial class Hospitalisation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _dateAdmission;
		
		private string _typeAdmission;
		
		private string _motifAdmission;
		
		private System.Nullable<int> _idMedecin;
		
		private string _nomAccompagnant;
		
		private string _prenomAccompagnant;
		
		private System.Nullable<int> _lientParente;
		
		private System.Nullable<System.DateTime> _dateEntreeAcc;
		
		private System.Nullable<System.DateTime> _dateSortieAcc;
		
		private string _motifSortie;
		
		private string _resultatSortie;
		
		private System.Nullable<System.DateTime> _dateDeces;
		
		private string _motifDeces;
		
		private int _idPatient;
		
		private System.Nullable<System.DateTime> _dateSortie;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateAdmissionChanging(System.Nullable<System.DateTime> value);
    partial void OndateAdmissionChanged();
    partial void OntypeAdmissionChanging(string value);
    partial void OntypeAdmissionChanged();
    partial void OnmotifAdmissionChanging(string value);
    partial void OnmotifAdmissionChanged();
    partial void OnidMedecinChanging(System.Nullable<int> value);
    partial void OnidMedecinChanged();
    partial void OnnomAccompagnantChanging(string value);
    partial void OnnomAccompagnantChanged();
    partial void OnprenomAccompagnantChanging(string value);
    partial void OnprenomAccompagnantChanged();
    partial void OnlientParenteChanging(System.Nullable<int> value);
    partial void OnlientParenteChanged();
    partial void OndateEntreeAccChanging(System.Nullable<System.DateTime> value);
    partial void OndateEntreeAccChanged();
    partial void OndateSortieAccChanging(System.Nullable<System.DateTime> value);
    partial void OndateSortieAccChanged();
    partial void OnmotifSortieChanging(string value);
    partial void OnmotifSortieChanged();
    partial void OnresultatSortieChanging(string value);
    partial void OnresultatSortieChanged();
    partial void OndateDecesChanging(System.Nullable<System.DateTime> value);
    partial void OndateDecesChanged();
    partial void OnmotifDecesChanging(string value);
    partial void OnmotifDecesChanged();
    partial void OnidPatientChanging(int value);
    partial void OnidPatientChanged();
    partial void OndateSortieChanging(System.Nullable<System.DateTime> value);
    partial void OndateSortieChanged();
    #endregion
		
		public Hospitalisation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateAdmission", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateAdmission
		{
			get
			{
				return this._dateAdmission;
			}
			set
			{
				if ((this._dateAdmission != value))
				{
					this.OndateAdmissionChanging(value);
					this.SendPropertyChanging();
					this._dateAdmission = value;
					this.SendPropertyChanged("dateAdmission");
					this.OndateAdmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeAdmission", DbType="VarChar(MAX)")]
		public string typeAdmission
		{
			get
			{
				return this._typeAdmission;
			}
			set
			{
				if ((this._typeAdmission != value))
				{
					this.OntypeAdmissionChanging(value);
					this.SendPropertyChanging();
					this._typeAdmission = value;
					this.SendPropertyChanged("typeAdmission");
					this.OntypeAdmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motifAdmission", DbType="VarChar(MAX)")]
		public string motifAdmission
		{
			get
			{
				return this._motifAdmission;
			}
			set
			{
				if ((this._motifAdmission != value))
				{
					this.OnmotifAdmissionChanging(value);
					this.SendPropertyChanging();
					this._motifAdmission = value;
					this.SendPropertyChanged("motifAdmission");
					this.OnmotifAdmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedecin", DbType="Int")]
		public System.Nullable<int> idMedecin
		{
			get
			{
				return this._idMedecin;
			}
			set
			{
				if ((this._idMedecin != value))
				{
					this.OnidMedecinChanging(value);
					this.SendPropertyChanging();
					this._idMedecin = value;
					this.SendPropertyChanged("idMedecin");
					this.OnidMedecinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomAccompagnant", DbType="VarChar(50)")]
		public string nomAccompagnant
		{
			get
			{
				return this._nomAccompagnant;
			}
			set
			{
				if ((this._nomAccompagnant != value))
				{
					this.OnnomAccompagnantChanging(value);
					this.SendPropertyChanging();
					this._nomAccompagnant = value;
					this.SendPropertyChanged("nomAccompagnant");
					this.OnnomAccompagnantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomAccompagnant", DbType="VarChar(50)")]
		public string prenomAccompagnant
		{
			get
			{
				return this._prenomAccompagnant;
			}
			set
			{
				if ((this._prenomAccompagnant != value))
				{
					this.OnprenomAccompagnantChanging(value);
					this.SendPropertyChanging();
					this._prenomAccompagnant = value;
					this.SendPropertyChanged("prenomAccompagnant");
					this.OnprenomAccompagnantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lientParente", DbType="Int")]
		public System.Nullable<int> lientParente
		{
			get
			{
				return this._lientParente;
			}
			set
			{
				if ((this._lientParente != value))
				{
					this.OnlientParenteChanging(value);
					this.SendPropertyChanging();
					this._lientParente = value;
					this.SendPropertyChanged("lientParente");
					this.OnlientParenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateEntreeAcc", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateEntreeAcc
		{
			get
			{
				return this._dateEntreeAcc;
			}
			set
			{
				if ((this._dateEntreeAcc != value))
				{
					this.OndateEntreeAccChanging(value);
					this.SendPropertyChanging();
					this._dateEntreeAcc = value;
					this.SendPropertyChanged("dateEntreeAcc");
					this.OndateEntreeAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateSortieAcc", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateSortieAcc
		{
			get
			{
				return this._dateSortieAcc;
			}
			set
			{
				if ((this._dateSortieAcc != value))
				{
					this.OndateSortieAccChanging(value);
					this.SendPropertyChanging();
					this._dateSortieAcc = value;
					this.SendPropertyChanged("dateSortieAcc");
					this.OndateSortieAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motifSortie", DbType="VarChar(MAX)")]
		public string motifSortie
		{
			get
			{
				return this._motifSortie;
			}
			set
			{
				if ((this._motifSortie != value))
				{
					this.OnmotifSortieChanging(value);
					this.SendPropertyChanging();
					this._motifSortie = value;
					this.SendPropertyChanged("motifSortie");
					this.OnmotifSortieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultatSortie", DbType="VarChar(MAX)")]
		public string resultatSortie
		{
			get
			{
				return this._resultatSortie;
			}
			set
			{
				if ((this._resultatSortie != value))
				{
					this.OnresultatSortieChanging(value);
					this.SendPropertyChanging();
					this._resultatSortie = value;
					this.SendPropertyChanged("resultatSortie");
					this.OnresultatSortieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateDeces", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateDeces
		{
			get
			{
				return this._dateDeces;
			}
			set
			{
				if ((this._dateDeces != value))
				{
					this.OndateDecesChanging(value);
					this.SendPropertyChanging();
					this._dateDeces = value;
					this.SendPropertyChanged("dateDeces");
					this.OndateDecesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motifDeces", DbType="VarChar(MAX)")]
		public string motifDeces
		{
			get
			{
				return this._motifDeces;
			}
			set
			{
				if ((this._motifDeces != value))
				{
					this.OnmotifDecesChanging(value);
					this.SendPropertyChanging();
					this._motifDeces = value;
					this.SendPropertyChanged("motifDeces");
					this.OnmotifDecesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPatient", DbType="Int NOT NULL")]
		public int idPatient
		{
			get
			{
				return this._idPatient;
			}
			set
			{
				if ((this._idPatient != value))
				{
					this.OnidPatientChanging(value);
					this.SendPropertyChanging();
					this._idPatient = value;
					this.SendPropertyChanged("idPatient");
					this.OnidPatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateSortie", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateSortie
		{
			get
			{
				return this._dateSortie;
			}
			set
			{
				if ((this._dateSortie != value))
				{
					this.OndateSortieChanging(value);
					this.SendPropertyChanging();
					this._dateSortie = value;
					this.SendPropertyChanged("dateSortie");
					this.OndateSortieChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Medecin")]
	public partial class Medecin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
		private string _prenom;
		
		private string _tel;
		
		private int _specialite;
		
		private System.Nullable<int> _serviceNom;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnspecialiteChanging(int value);
    partial void OnspecialiteChanged();
    partial void OnserviceNomChanging(System.Nullable<int> value);
    partial void OnserviceNomChanged();
    #endregion
		
		public Medecin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(15)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialite", DbType="Int NOT NULL")]
		public int specialite
		{
			get
			{
				return this._specialite;
			}
			set
			{
				if ((this._specialite != value))
				{
					this.OnspecialiteChanging(value);
					this.SendPropertyChanging();
					this._specialite = value;
					this.SendPropertyChanged("specialite");
					this.OnspecialiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceNom", DbType="Int")]
		public System.Nullable<int> serviceNom
		{
			get
			{
				return this._serviceNom;
			}
			set
			{
				if ((this._serviceNom != value))
				{
					this.OnserviceNomChanging(value);
					this.SendPropertyChanging();
					this._serviceNom = value;
					this.SendPropertyChanged("serviceNom");
					this.OnserviceNomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medecin")]
	public partial class Medecin1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
		private string _prenom;
		
		private string _tel;
		
		private int _specialite;
		
		private System.Nullable<int> _serviceNom;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnspecialiteChanging(int value);
    partial void OnspecialiteChanged();
    partial void OnserviceNomChanging(System.Nullable<int> value);
    partial void OnserviceNomChanged();
    #endregion
		
		public Medecin1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(15)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialite", DbType="Int NOT NULL")]
		public int specialite
		{
			get
			{
				return this._specialite;
			}
			set
			{
				if ((this._specialite != value))
				{
					this.OnspecialiteChanging(value);
					this.SendPropertyChanging();
					this._specialite = value;
					this.SendPropertyChanged("specialite");
					this.OnspecialiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviceNom", DbType="Int")]
		public System.Nullable<int> serviceNom
		{
			get
			{
				return this._serviceNom;
			}
			set
			{
				if ((this._serviceNom != value))
				{
					this.OnserviceNomChanging(value);
					this.SendPropertyChanging();
					this._serviceNom = value;
					this.SendPropertyChanged("serviceNom");
					this.OnserviceNomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Patient")]
	public partial class Patient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nom;
		
		private string _prenom;
		
		private System.Nullable<System.DateTime> _dateNaissance;
		
		private System.Nullable<int> _sexe;
		
		private string _adresse;
		
		private System.Nullable<int> _situationFamilliale;
		
		private string _assuranceMedical;
		
		private string _codeAssurance;
		
		private string _tel;
		
		private string _nomPere;
		
		private string _nomMere;
		
		private string _nomPersonnePrevenir;
		
		private string _telPersonnePrevenir;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OndateNaissanceChanging(System.Nullable<System.DateTime> value);
    partial void OndateNaissanceChanged();
    partial void OnsexeChanging(System.Nullable<int> value);
    partial void OnsexeChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnsituationFamillialeChanging(System.Nullable<int> value);
    partial void OnsituationFamillialeChanged();
    partial void OnassuranceMedicalChanging(string value);
    partial void OnassuranceMedicalChanged();
    partial void OncodeAssuranceChanging(string value);
    partial void OncodeAssuranceChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnnomPereChanging(string value);
    partial void OnnomPereChanged();
    partial void OnnomMereChanging(string value);
    partial void OnnomMereChanged();
    partial void OnnomPersonnePrevenirChanging(string value);
    partial void OnnomPersonnePrevenirChanged();
    partial void OntelPersonnePrevenirChanging(string value);
    partial void OntelPersonnePrevenirChanged();
    #endregion
		
		public Patient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNaissance", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateNaissance
		{
			get
			{
				return this._dateNaissance;
			}
			set
			{
				if ((this._dateNaissance != value))
				{
					this.OndateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._dateNaissance = value;
					this.SendPropertyChanged("dateNaissance");
					this.OndateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexe", DbType="Int")]
		public System.Nullable<int> sexe
		{
			get
			{
				return this._sexe;
			}
			set
			{
				if ((this._sexe != value))
				{
					this.OnsexeChanging(value);
					this.SendPropertyChanging();
					this._sexe = value;
					this.SendPropertyChanged("sexe");
					this.OnsexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(MAX)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situationFamilliale", DbType="Int")]
		public System.Nullable<int> situationFamilliale
		{
			get
			{
				return this._situationFamilliale;
			}
			set
			{
				if ((this._situationFamilliale != value))
				{
					this.OnsituationFamillialeChanging(value);
					this.SendPropertyChanging();
					this._situationFamilliale = value;
					this.SendPropertyChanged("situationFamilliale");
					this.OnsituationFamillialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assuranceMedical", DbType="VarChar(50)")]
		public string assuranceMedical
		{
			get
			{
				return this._assuranceMedical;
			}
			set
			{
				if ((this._assuranceMedical != value))
				{
					this.OnassuranceMedicalChanging(value);
					this.SendPropertyChanging();
					this._assuranceMedical = value;
					this.SendPropertyChanged("assuranceMedical");
					this.OnassuranceMedicalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeAssurance", DbType="VarChar(MAX)")]
		public string codeAssurance
		{
			get
			{
				return this._codeAssurance;
			}
			set
			{
				if ((this._codeAssurance != value))
				{
					this.OncodeAssuranceChanging(value);
					this.SendPropertyChanging();
					this._codeAssurance = value;
					this.SendPropertyChanged("codeAssurance");
					this.OncodeAssuranceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(15)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPere", DbType="VarChar(50)")]
		public string nomPere
		{
			get
			{
				return this._nomPere;
			}
			set
			{
				if ((this._nomPere != value))
				{
					this.OnnomPereChanging(value);
					this.SendPropertyChanging();
					this._nomPere = value;
					this.SendPropertyChanged("nomPere");
					this.OnnomPereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomMere", DbType="VarChar(50)")]
		public string nomMere
		{
			get
			{
				return this._nomMere;
			}
			set
			{
				if ((this._nomMere != value))
				{
					this.OnnomMereChanging(value);
					this.SendPropertyChanging();
					this._nomMere = value;
					this.SendPropertyChanged("nomMere");
					this.OnnomMereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomPersonnePrevenir", DbType="VarChar(50)")]
		public string nomPersonnePrevenir
		{
			get
			{
				return this._nomPersonnePrevenir;
			}
			set
			{
				if ((this._nomPersonnePrevenir != value))
				{
					this.OnnomPersonnePrevenirChanging(value);
					this.SendPropertyChanging();
					this._nomPersonnePrevenir = value;
					this.SendPropertyChanged("nomPersonnePrevenir");
					this.OnnomPersonnePrevenirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telPersonnePrevenir", DbType="VarChar(15)")]
		public string telPersonnePrevenir
		{
			get
			{
				return this._telPersonnePrevenir;
			}
			set
			{
				if ((this._telPersonnePrevenir != value))
				{
					this.OntelPersonnePrevenirChanging(value);
					this.SendPropertyChanging();
					this._telPersonnePrevenir = value;
					this.SendPropertyChanged("telPersonnePrevenir");
					this.OntelPersonnePrevenirChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prescription")]
	public partial class Prescription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _idPatient;
		
		private string _note;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnidPatientChanging(System.Nullable<int> value);
    partial void OnidPatientChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
		
		public Prescription()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPatient", DbType="Int")]
		public System.Nullable<int> idPatient
		{
			get
			{
				return this._idPatient;
			}
			set
			{
				if ((this._idPatient != value))
				{
					this.OnidPatientChanging(value);
					this.SendPropertyChanging();
					this._idPatient = value;
					this.SendPropertyChanged("idPatient");
					this.OnidPatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="VarChar(MAX)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rdv")]
	public partial class Rdv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _code;
		
		private int _idMedecin;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _idService;
		
		private System.Nullable<int> _idPatient;
		
		private System.Nullable<int> _annule;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(int value);
    partial void OncodeChanged();
    partial void OnidMedecinChanging(int value);
    partial void OnidMedecinChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnidServiceChanging(System.Nullable<int> value);
    partial void OnidServiceChanged();
    partial void OnidPatientChanging(System.Nullable<int> value);
    partial void OnidPatientChanged();
    partial void OnannuleChanging(System.Nullable<int> value);
    partial void OnannuleChanged();
    #endregion
		
		public Rdv()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Int NOT NULL")]
		public int code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedecin", DbType="Int NOT NULL")]
		public int idMedecin
		{
			get
			{
				return this._idMedecin;
			}
			set
			{
				if ((this._idMedecin != value))
				{
					this.OnidMedecinChanging(value);
					this.SendPropertyChanging();
					this._idMedecin = value;
					this.SendPropertyChanged("idMedecin");
					this.OnidMedecinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idService", DbType="Int")]
		public System.Nullable<int> idService
		{
			get
			{
				return this._idService;
			}
			set
			{
				if ((this._idService != value))
				{
					this.OnidServiceChanging(value);
					this.SendPropertyChanging();
					this._idService = value;
					this.SendPropertyChanged("idService");
					this.OnidServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPatient", DbType="Int")]
		public System.Nullable<int> idPatient
		{
			get
			{
				return this._idPatient;
			}
			set
			{
				if ((this._idPatient != value))
				{
					this.OnidPatientChanging(value);
					this.SendPropertyChanging();
					this._idPatient = value;
					this.SendPropertyChanged("idPatient");
					this.OnidPatientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annule", DbType="Int")]
		public System.Nullable<int> annule
		{
			get
			{
				return this._annule;
			}
			set
			{
				if ((this._annule != value))
				{
					this.OnannuleChanging(value);
					this.SendPropertyChanging();
					this._annule = value;
					this.SendPropertyChanged("annule");
					this.OnannuleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
